# Generated by Django 4.1.2 on 2022-10-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('origin_url', models.TextField()),
                ('token', models.TextField()),
            ],
            options={
                'db_table': 'url',
            },
        ),
    ]
